spring.application.name=customer-feedback-system
spring.datasource.url=jdbc:mysql://localhost:3306/feedbackdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090